name: Continuous Integration

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Install and Build
      run: |
        yarn install
        yarn build
    - name: Non Visual Tests
      run: yarn test
    - uses: ./ # Uses an action in the root directory
    - name: Visual Tests
      uses: smorgrav/react-firebase-material-template@master
      with:
        args: yarn local & curl --retry 10 --retry-delay 11 --retry-max-time 120 --max-time 8 --retry-connrefused localhost:3000 && yarn visual
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build

  deploy:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
