name: Continuous Integration

on:
  push:
    branches:
      - master

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Yarn Install
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: yarn install
    - name: Yarn Build
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: yarn build
    - name: Yarn Test
      uses: ianwalter/puppeteer@v2.0.0
      with:
        entrypoint: /bin/sh
        args: |
          -c "\
          yarn start & \
          sleep 120 &&
          yarn test"
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build

  deploy:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: build
      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting --non-interactive
