name: Node CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: yarn
    - name: Test
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: echo hello
    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist

  deploy:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifacts
        uses: actions/download-artifact@master
        with:
          name: dist
      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting --non-interactive
